name: sayari
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # services & api
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_database: ^10.5.1
  firebase_storage: ^11.7.1
  cloud_functions: ^4.7.1
  google_sign_in: ^6.1.4
  # local data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # files
  file_picker: ^8.0.0+1
  open_filex: ^4.3.4
  file_saver: ^0.2.12
  extended_image: any
  # state
  provider: ^6.0.3
  # navigation
  go_router: ^14.2.7
  # style & assets
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  responsive_sizer: ^3.1.1
  syncfusion_flutter_datepicker: ^25.1.39
  reorderable_grid: ^1.0.10
  styled_text: ^8.1.0
  just_the_tooltip: ^0.0.12
  scrollable_positioned_list: ^0.3.8
  flutter_keyboard_visibility: ^6.0.0
  flutter_quill: ^9.3.3
  confetti: ^0.7.0
  flutter_spinkit: ^5.2.1
  # notifications
  awesome_notifications: ^0.9.3+1
  bot_toast: ^4.0.4
  # others
  collection: ^1.17.1
  url_launcher: ^6.1.10
  intl: ^0.19.0
  flutter_cache_manager: ^3.3.1
  requests: ^4.7.0
  permission_handler: ^11.0.1
  flutter_tts: ^4.0.2
  flutter_blue_plus: ^1.32.5
  flutter_web_bluetooth: ^0.2.3
  fl_chart: ^0.67.0
  photo_view: ^0.15.0
  pdf: ^3.10.8
  file: any

dependency_overrides:
  # intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/files/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sayari.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/sayari.png"

flutter_native_splash:
  # color: "#fafafc"
  # color_dark: "#1b1d1c"
  background_image: "assets/images/dune.jpg"
  image: "assets/images/sayari.png"
  fullscreen: true
#
# dart run flutter_launcher_icons
# dart run flutter_native_splash:create
# dart run change_app_package_name:main com.sayari.app

