Map<String, String> fileTypeImages = {
  'pdf': 'assets/files/pdf.png',
  'doc': 'assets/files/doc.png',
  'ppt': 'assets/files/ppt.png',
  'xls': 'assets/files/xls.png',
  'zip': 'assets/files/zip.png',
  'tar': 'assets/files/zip.png',
  'rar': 'assets/files/zip.png',
  'mp3': 'assets/files/music.png',
  'dart': 'assets/files/css.png',
  'js': 'assets/files/css.png',
  'html': 'assets/files/css.png',
  'css': 'assets/files/css.png',
  'py': 'assets/files/css.png',
  'c': 'assets/files/css.png',
  'cpp': 'assets/files/css.png',
  'ino': 'assets/files/css.png',
  'apk': 'assets/files/apk.png',
  'txt': 'assets/files/txt.png',
};
